// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace merigurumiblog
{
    public partial class author
    {
        public author()
        {
            authorfollow = new HashSet<authorfollow>();
            post = new HashSet<post>();
        }

        [Key]
        public int authorid { get; set; }
        [Required]
        [StringLength(50)]
        public string name { get; set; }
        [Required]
        [StringLength(50)]
        public string lastname { get; set; }
        [StringLength(50)]
        public string mailadress { get; set; }
        public string display { get; set; }
        public bool? gender { get; set; }

        [InverseProperty("author")]
        public virtual ICollection<authorfollow> authorfollow { get; set; }
        [InverseProperty("author")]
        public virtual ICollection<post> post { get; set; }
    }
}