// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace merigurumiblog
{
    public partial class authorfollow
    {
        [Key]
        public int authorid { get; set; }
        [Key]
        public int userid { get; set; }

        [ForeignKey(nameof(authorid))]
        [InverseProperty("authorfollow")]
        public virtual author author { get; set; }
        [ForeignKey(nameof(userid))]
        [InverseProperty("authorfollow")]
        public virtual user user { get; set; }
    }
}