// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace merigurumiblog
{
    public partial class category
    {
        public category()
        {
            post = new HashSet<post>();
        }

        [Key]
        public int categoryid { get; set; }
        [Required]
        [StringLength(50)]
        public string name { get; set; }
        [StringLength(500)]
        public string display { get; set; }

        [InverseProperty("category")]
        public virtual ICollection<post> post { get; set; }
    }
}