// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace merigurumiblog
{
    public partial class comment
    {
        [Key]
        public int commentid { get; set; }
        [Column("comment")]
        [StringLength(1500)]
        public string comment1 { get; set; }
        public int? postid { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? dateadded { get; set; }
        [StringLength(150)]
        public string namelastname { get; set; }
        public int? likes { get; set; }

        [ForeignKey(nameof(postid))]
        [InverseProperty("comment")]
        public virtual post post { get; set; }
    }
}