// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace merigurumiblog
{
    public partial class picture
    {
        [Key]
        public int pictureid { get; set; }
        [StringLength(250)]
        public string smallsize { get; set; }
        [StringLength(250)]
        public string middlesize { get; set; }
        [StringLength(250)]
        public string bigsize { get; set; }
        [StringLength(250)]
        public string video { get; set; }
        public int? postid { get; set; }

        [ForeignKey(nameof(postid))]
        [InverseProperty("picture")]
        public virtual post post { get; set; }
    }
}