// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace merigurumiblog
{
    public partial class post
    {
        public post()
        {
            comment = new HashSet<comment>();
            picture = new HashSet<picture>();
            posttag = new HashSet<posttag>();
        }

        [Key]
        public int postid { get; set; }
        [Required]
        [StringLength(100)]
        public string postname { get; set; }
        [Required]
        public string postcontent { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime postdate { get; set; }
        public int categoryid { get; set; }
        public int display { get; set; }
        public int likes { get; set; }
        public int authorid { get; set; }

        [ForeignKey(nameof(authorid))]
        [InverseProperty("post")]
        public virtual author author { get; set; }
        [ForeignKey(nameof(categoryid))]
        [InverseProperty("post")]
        public virtual category category { get; set; }
        [InverseProperty("post")]
        public virtual ICollection<comment> comment { get; set; }
        [InverseProperty("post")]
        public virtual ICollection<picture> picture { get; set; }
        [InverseProperty("post")]
        public virtual ICollection<posttag> posttag { get; set; }
    }
}