// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace merigurumiblog
{
    public partial class posttag
    {
        [Key]
        public int postid { get; set; }
        [Key]
        public int tagid { get; set; }

        [ForeignKey(nameof(postid))]
        [InverseProperty("posttag")]
        public virtual post post { get; set; }
        [ForeignKey(nameof(tagid))]
        [InverseProperty("posttag")]
        public virtual tag tag { get; set; }
    }
}