// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace merigurumiblog
{
    public partial class tag
    {
        public tag()
        {
            posttag = new HashSet<posttag>();
        }

        [Key]
        public int tagid { get; set; }
        [StringLength(50)]
        public string tagname { get; set; }

        [InverseProperty("tag")]
        public virtual ICollection<posttag> posttag { get; set; }
    }
}