// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace merigurumiblog
{
    public partial class user
    {
        public user()
        {
            authorfollow = new HashSet<authorfollow>();
        }

        [Key]
        public int userid { get; set; }
        [Required]
        [StringLength(50)]
        public string name { get; set; }
        [Required]
        [StringLength(50)]
        public string lastname { get; set; }
        [Required]
        [StringLength(50)]
        public string username { get; set; }
        [Required]
        [StringLength(200)]
        public string password { get; set; }
        [Required]
        [StringLength(50)]
        public string mailadress { get; set; }
        public bool? gender { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? dateofbirth { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime registeringdate { get; set; }

        [InverseProperty("user")]
        public virtual ICollection<authorfollow> authorfollow { get; set; }
    }
}