// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace merigurumiblog
{
    public partial class Author
    {
        public Author()
        {
            Authorfollow = new HashSet<Authorfollow>();
            Post = new HashSet<Post>();
        }

        public int Authorid { get; set; }
        public string Name { get; set; }
        public string Lastname { get; set; }
        public string Mailadress { get; set; }
        public string Display { get; set; }
        public bool? Gender { get; set; }

        public virtual ICollection<Authorfollow> Authorfollow { get; set; }
        public virtual ICollection<Post> Post { get; set; }
    }
}