// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace merigurumiblog
{
    public partial class Authorfollow
    {
        public int Authorid { get; set; }
        public int Userid { get; set; }

        public virtual Author Author { get; set; }
        public virtual User User { get; set; }
    }
}