// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace merigurumiblog
{
    public partial class Category
    {
        public Category()
        {
            Post = new HashSet<Post>();
        }

        public int Categoryid { get; set; }
        public string Name { get; set; }
        public string Display { get; set; }

        public virtual ICollection<Post> Post { get; set; }
    }
}