// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace merigurumiblog
{
    public partial class Comment
    {
        public int Commentid { get; set; }
        public string Comment1 { get; set; }
        public int? Postid { get; set; }
        public DateTime? Dateadded { get; set; }
        public string Namelastname { get; set; }
        public int? Likes { get; set; }

        public virtual Post Post { get; set; }
    }
}