// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace merigurumiblog
{
    public partial class Picture
    {
        public int Pictureid { get; set; }
        public string Smallsize { get; set; }
        public string Middlesize { get; set; }
        public string Bigsize { get; set; }
        public string Video { get; set; }
        public int? Postid { get; set; }

        public virtual Post Post { get; set; }
    }
}