// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace merigurumiblog
{
    public partial class Post
    {
        public Post()
        {
            Comment = new HashSet<Comment>();
            Picture = new HashSet<Picture>();
            Posttag = new HashSet<Posttag>();
        }

        public int Postid { get; set; }
        public string Postname { get; set; }
        public string Postcontent { get; set; }
        public DateTime Postdate { get; set; }
        public int Categoryid { get; set; }
        public int Display { get; set; }
        public int Likes { get; set; }
        public int Authorid { get; set; }

        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<Picture> Picture { get; set; }
        public virtual ICollection<Posttag> Posttag { get; set; }
    }
}