// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace merigurumiblog
{
    public partial class Tag
    {
        public Tag()
        {
            Posttag = new HashSet<Posttag>();
        }

        public int Tagid { get; set; }
        public string Tagname { get; set; }

        public virtual ICollection<Posttag> Posttag { get; set; }
    }
}