// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace merigurumiblog
{
    public partial class User
    {
        public User()
        {
            Authorfollow = new HashSet<Authorfollow>();
        }

        public int Userid { get; set; }
        public string Name { get; set; }
        public string Lastname { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Mailadress { get; set; }
        public bool? Gender { get; set; }
        public DateTime? Dateofbirth { get; set; }
        public DateTime Registeringdate { get; set; }

        public virtual ICollection<Authorfollow> Authorfollow { get; set; }
    }
}